app:
  title: The Miami Public Space Challenge
  name: The Miami Public Space Challenge
  meta_description: _('The Miami Foundation and our partners created the Our Miami Public Space Challenge to discover the best ideas for improving, creating, and activating local public spaces.')

map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 25.79571825588276
      lng: -80.24002075195312
    zoom: 12
    minZoom: 10
    maxZoom: 18
  layers:
    # First version of custom tiles
    # - url: https://api.mapbox.com/styles/v1/miamipsc/ciz9puq2a00502rmuot3sxl0a/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoibWlhbWlwc2MiLCJhIjoiY2l5N3RjY202MDA4ajJ3cW05ZGg1eDloOCJ9.7Q8BG1yF7iHPASyYFp0hsg

    # Second version of custom tiles
    - type: mapbox
      style: mapbox://styles/miamipsc/cjue1ils20hec1fs17esm5bf6

    # Light, bare style
    # - url: https://api.mapbox.com/styles/v1/miamipsc/ciyn6joil007l2smg79w5j53b/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoibWlhbWlwc2MiLCJhIjoiY2l5N3RjY202MDA4ajJ3cW05ZGg1eDloOCJ9.7Q8BG1yF7iHPASyYFp0hsg

    # Plain Mapbox tiles
    #- url: https://api.mapbox.com/styles/v1/miamipsc/cizrpvslt001f2snsjc6i6xn4/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoibWlhbWlwc2MiLCJhIjoiY2l5N3RjY202MDA4ajJ3cW05ZGg1eDloOCJ9.7Q8BG1yF7iHPASyYFp0hsg

      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

place_types:

  Winner2013:
    label: _(2013 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]
  Winner2014:
    label: _(2014 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]
  Winner2015:
    label: _(2015 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]
  Winner2016:
    label: _(2016 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]
  Winner2017:
    label: _(2017 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]

  pedestrian:
    label: _(Walking)
    rules:
      - condition: '"{{location_type}}" === "pedestrian" && ("{{ff}}" === "1" || "{{ff}}" === "2") && !{{layer.focused}}'
        style:
          fillColor: '#A0B4C6'
          fillOpacity: 1
          radius: 6
          color: 'black'
          opacity: 1
          weight: 2
      - condition: '"{{location_type}}" === "pedestrian" && !{{layer.focused}}'
        style:
          fillColor: '#A0B4C6'
          fillOpacity: 1
          radius: 5
          color: 'black'
          opacity: 1
          weight: 2
      - condition: '"{{location_type}}" === "pedestrian" && {{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-pedestrian.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [45, 54]
          shadowSize: [41, 41]
          iconAnchor: [22, 54]
  biking:
    label: _(Biking)
    rules:
      - condition: '"{{location_type}}" === "biking" && ("{{ff}}" === "1" || "{{ff}}" === "2") && !{{layer.focused}}'
        style:
          fillColor: '#C4ED52'
          fillOpacity: 1
          radius: 6
          color: 'black'
          opacity: 1
          weight: 2
      - condition: '"{{location_type}}" === "biking" && !{{layer.focused}}'
        style:
          fillColor: '#C4ED52'
          fillOpacity: 1
          radius: 5
          color: 'black'
          opacity: 1
          weight: 2
      - condition: '"{{location_type}}" === "biking" && {{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-biking.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [45, 54]
          shadowSize: [41, 41]
          iconAnchor: [22, 54]
  streetsidewalk:
    label: _(Streets & Sidewalks)
    rules:
      - condition: '"{{location_type}}" === "streetsidewalk" && ("{{ff}}" === "1" || "{{ff}}" === "2") && !{{layer.focused}}'
        style:
          fillColor: '#FFD614'
          fillOpacity: 1
          radius: 6
          color: 'black'
          opacity: 1
          weight: 2
      - condition: '"{{location_type}}" === "streetsidewalk" && !{{layer.focused}}'
        style:
          fillColor: '#FFD614'
          fillOpacity: 1
          radius: 5
          color: 'black'
          opacity: 1
          weight: 2
      - condition: '"{{location_type}}" === "streetsidewalk" && {{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-streetsidewalk.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [50, 60]
          shadowSize: [41, 41]
          iconAnchor: [25, 60]
  transit:
    label: _(Public Transit)
    rules:
      - condition: '"{{location_type}}" === "transit" && ("{{ff}}" === "1" || "{{ff}}" === "2") && !{{layer.focused}}'
        style:
          fillColor: '#B75AB8'
          fillOpacity: 1
          radius: 6
          color: 'black'
          opacity: 1
          weight: 2
      - condition: '"{{location_type}}" === "transit" && !{{layer.focused}}'
        style:
          fillColor: '#B75AB8'
          fillOpacity: 1
          radius: 5
          color: 'black'
          opacity: 1
          weight: 2
      - condition: '"{{location_type}}" === "transit" && {{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-transit.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [45, 54]
          shadowSize: [41, 41]
          iconAnchor: [22, 54]

activity:
  enabled: false
  interval: 30000

place:
  adding_supported:
    from: '2019-04-16 09:00 -0400'
    until: '2019-05-17 00:00 -0400'
  add_button_label: _(Add an idea)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List Ideas)
  show_map_button_label: _(Show the Map)
  action_text: _(suggested)
  title: _(Tell us more...)
  action_text: _(suggested)
  anonymous_name: _(Someone)
  submit_button_label: _(Post it to the map)
  items:
    - prompt: _(* The title of my project is...)
      type: textarea
      name: title
      optional: false
      label: _(The title of my project is...)
      attrs:
        - key: placeholder
          value: _(Help us with a great name to identify your project.)
        - key: required
          value: required
        - key: maxlength
          value: 100
    - prompt: _(* My idea to improve this place...)
      type: textarea
      name: description
      optional: false
      label: _(My idea to improve this place...)
      attrs:
        - key: placeholder
          value: _(Think low-cost, block-focused, short-term, street-scale or smaller.)
        - key: required
          value: required
        - key: maxlength
          value: 750
    - prompt: _(* So that people could...)
      type: textarea
      name: details
      optional: false
      label: _(So that people could...)
      attrs:
        - key: placeholder
          value: _(Tell us why this idea would help make our Miami better.)
        - key: required
          value: required
        - key: maxlength
          value: 750
    - prompt: _(* My project will improve...)
      label: _(Project type)
      type: radiogroup
      options:
        - label: _(Walking)
          value: pedestrian
        - label: _(Biking)
          value: biking
        - label: _(Streets & Sidewalks)
          value: streetsidewalk
        - label: _(Public Transit)
          value: transit
      attrs:
      - key: required
        value: required
      name: location_type
    - prompt: _(The approximate address or location of my project is...)
      type: text
      name: address
      optional: false
      label: _(The approximate address or location of my project is...)
      attrs:
        - key: placeholder
          value: _(Let us know where you mean.)
        - key: maxlength
          value: 160
    - prompt: _(Show us with a picture)
      inputfile_label: _(Upload an image)
      type: file
      name: my_image
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Add a link)
      type: text
      name: infolink
      attrs:
        - key: placeholder
          value: _(Add a related link (an example or more info))
        - key: size
          value: 30
    - type: hidden
      name: private-conf
      attrs:
        - key: value
          value: "Not sent"
    - prompt: _(* Your Name)
      label: _(Suggested by)
      type: text
      name: submitter_name
      attrs:
        - key: placeholder
          value: _(Person/Org to be credited for idea publicly)
        - key: size
          value: 30
        - key: required
          value: required
    - prompt: _(Your organization)
      label: _(Organization)
      type: text
      name: organization
      attrs:
        - key: placeholder
          value: _(Your organization)
        - key: size
          value: 30
    - prompt: _(* Your email)
      type: email
      optional: false
      name: private-email
      attrs:
        - key: placeholder
          value: _(Your email will not be shown publicly)
        - key: size
          value: 30
        - key: required
          value: required
    - prompt: _(Your phone number)
      type: text
      name: private-phone
      attrs:
        - key: placeholder
          value: _(Your number will not be shown publicly)
        - key: size
          value: 30

survey:
  submission_type: comments
  adding_supported:
    from: '2019-04-16 09:00 -0400'
    until: '2019-05-17 00:00 -0400'

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  adding_supported:
    from: '2019-04-16 09:00 -0400'
    until: '2019-05-17 00:00 -0400'
  submit_btn_text: _(Like This!)
  response_name: _(like)
  response_plural_name: _(likes)
  action_text: liked
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true
  - title: _(FAQ)
    slug: faq
    name: faq
  - title: _(Workshops & Resources)
    slug: resources
    name: resources
  - title: Filter Ideas
    slug: filter-type
    pages:
      - title: All
        external: true
        url: /filter/all
      - title: _(Walking)
        url: /filter/pedestrian
        external: true
      - title: _(Biking)
        url: /filter/biking
        external: true
      - title: _(Streets & Sidewalks)
        url: /filter/streetsidewalk
        external: true
      - title: _(Public Transit)
        url: /filter/transit
        external: true
  # - title: _(Finalists)
  #   slug: finalists
  #   name: finalists
  # - title: _(2016 Winners)
  #   slug: winners
  #   name: winners

notifications:
  on_new_place: true
  submitter_email_field: private-email
