app:
  title: OurMiami
  name: OurMiami
  meta_description: _('The Miami Foundation and our partners created the Our Miami Public Space Challenge to discover the best ideas for improving, creating, and activating local public spaces.')
  list_enabled: true

map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 25.79571825588276
      lng: -80.24002075195312
    zoom: 12
    minZoom: 10
    maxZoom: 18
  layers:
    # First version of custom tiles
    # - url: https://api.mapbox.com/styles/v1/miamipsc/ciz9puq2a00502rmuot3sxl0a/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoibWlhbWlwc2MiLCJhIjoiY2l5N3RjY202MDA4ajJ3cW05ZGg1eDloOCJ9.7Q8BG1yF7iHPASyYFp0hsg

    # Second version of custom tiles
    - url: https://api.mapbox.com/styles/v1/miamipsc/ciztt89db005c2rlrv5k9dzrv/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoibWlhbWlwc2MiLCJhIjoiY2l5N3RjY202MDA4ajJ3cW05ZGg1eDloOCJ9.7Q8BG1yF7iHPASyYFp0hsg

    # Light, bare style
    # - url: https://api.mapbox.com/styles/v1/miamipsc/ciyn6joil007l2smg79w5j53b/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoibWlhbWlwc2MiLCJhIjoiY2l5N3RjY202MDA4ajJ3cW05ZGg1eDloOCJ9.7Q8BG1yF7iHPASyYFp0hsg

    # Plain Mapbox tiles
    #- url: https://api.mapbox.com/styles/v1/miamipsc/cizrpvslt001f2snsjc6i6xn4/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoibWlhbWlwc2MiLCJhIjoiY2l5N3RjY202MDA4ajJ3cW05ZGg1eDloOCJ9.7Q8BG1yF7iHPASyYFp0hsg

      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

place_types:
  Winner2013:
    label: _(2013 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]
  Winner2014:
    label: _(2014 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]
  Winner2015:
    label: _(2015 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]
  Winner2016:
    label: _(2016 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]
  Winner2017:
    label: _(2017 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]

activity:
  enabled: false

place:
  adding_supported: false
  add_button_label: _(Add an idea)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List Ideas)
  show_map_button_label: _(Show the Map)
  action_text: _(suggested)
  title: _(Tell us more...)
  action_text: _(suggested)
  anonymous_name: _(Someone)
  submit_button_label: _(Post it to the map)
  items: []

survey:
  submission_type: comments
  adding_supported: false

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items: []

support:
  submission_type: support
  adding_supported: false
  submit_btn_text: _(Like This!)
  response_name: _(like)
  response_plural_name: _(likes)
  action_text: liked
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview-winners
    start_page: true
  - title: _(FAQ)
    slug: faq
    name: faq
  - title: _(Workshops & Resources)
    slug: resources
    name: resources
  - title: Filter Ideas
    slug: filter-type
    pages:
      - title: All
        external: true
        url: /filter/all
      - title: _(Parks & Natural Areas)
        url: /filter/ParksAndNaturalAreas
        external: true
      - title: _(Greenways & Blueways)
        url: /filter/GreenwaysAndBlueways
        external: true
      - title: _(Safe Routes to Parks)
        url: /filter/SafeRoutesToParks
        external: true
      - title: _(Public Spaces)
        url: /filter/PublicSpaces
        external: true
  # - title: _(Finalists)
  #   slug: finalists
  #   name: finalists
  - title: _(2017 Challenge Winners)
    slug: winners
    name: winners

notifications:
  on_new_place: true
  submitter_email_field: private-email
