app:
  title: OurMiami
  name: OurMiami
  meta_description: _('The Miami Foundation and our partners created the Our Miami Public Space Challenge to discover the best ideas for improving, creating, and activating local public spaces.')
  list_enabled: true

map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 25.79571825588276
      lng: -80.24002075195312
    zoom: 12
    minZoom: 10
    maxZoom: 18
  layers:
    # First version of custom tiles
    # - url: https://api.mapbox.com/styles/v1/miamipsc/ciz9puq2a00502rmuot3sxl0a/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoibWlhbWlwc2MiLCJhIjoiY2l5N3RjY202MDA4ajJ3cW05ZGg1eDloOCJ9.7Q8BG1yF7iHPASyYFp0hsg

    # Second version of custom tiles
    - url: https://api.mapbox.com/styles/v1/miamipsc/ciztt89db005c2rlrv5k9dzrv/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoibWlhbWlwc2MiLCJhIjoiY2l5N3RjY202MDA4ajJ3cW05ZGg1eDloOCJ9.7Q8BG1yF7iHPASyYFp0hsg

    # Light, bare style
    # - url: https://api.mapbox.com/styles/v1/miamipsc/ciyn6joil007l2smg79w5j53b/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoibWlhbWlwc2MiLCJhIjoiY2l5N3RjY202MDA4ajJ3cW05ZGg1eDloOCJ9.7Q8BG1yF7iHPASyYFp0hsg

    # Plain Mapbox tiles
    #- url: https://api.mapbox.com/styles/v1/miamipsc/cizrpvslt001f2snsjc6i6xn4/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoibWlhbWlwc2MiLCJhIjoiY2l5N3RjY202MDA4ajJ3cW05ZGg1eDloOCJ9.7Q8BG1yF7iHPASyYFp0hsg

      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

place_types:
  Winner2013:
    label: _(2013 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]
  Winner2014:
    label: _(2014 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]
  Winner2015:
    label: _(2015 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]
  Winner2016:
    label: _(2016 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]
  Winner2017:
    label: _(2017 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]
  Winner2018:
    label: _(2018 Winner)
    rules:
      - condition: '!{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/dot-star.png
          iconSize: [20, 20]
          iconAnchor: [10, 10]
      - condition: '{{layer.focused}}'
        icon:
          iconUrl: /static/css/images/markers/marker-star.png
          iconSize: [40, 40]
          iconAnchor: [20, 20]

activity:
  enabled: false

place:
  adding_supported: false
  add_button_label: _(Add an idea)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List Past Winners)
  show_map_button_label: _(Show the Map)
  action_text: _(suggested)
  title: _(Tell us more...)
  action_text: _(suggested)
  anonymous_name: _(Someone)
  submit_button_label: _(Post it to the map)
  items:
    - prompt: _(* The title of my project is...)
      type: textarea
      name: title
      optional: false
      label: _(The title of my project is...)
      attrs:
        - key: placeholder
          value: _(Help us with a great name to identify your project.)
        - key: required
          value: required
        - key: maxlength
          value: 100
    - prompt: _(* My idea to improve this place...)
      type: textarea
      name: description
      optional: false
      label: _(My idea to improve this place...)
      attrs:
        - key: placeholder
          value: _(Think low-cost, block-focused, short-term, street-scale or smaller.)
        - key: required
          value: required
        - key: maxlength
          value: 750
    - prompt: _(* So that people could...)
      type: textarea
      name: details
      optional: false
      label: _(So that people could...)
      attrs:
        - key: placeholder
          value: _(Tell us why this idea would help make our Miami better.)
        - key: required
          value: required
        - key: maxlength
          value: 750
    - prompt: _(* My project will improve...)
      label: _(Project type)
      type: radiogroup
      options:
        - label: _(Parks & Natural Areas)
          value: ParksAndNaturalAreas
        - label: _(Greenways & Blueways)
          value: GreenwaysAndBlueways
        - label: _(Safe Routes to Parks)
          value: SafeRoutesToParks
        - label: _(Public Spaces)
          value: PublicSpaces
      attrs:
      - key: required
        value: required
      name: location_type
    - prompt: _(The approximate address or location of my project is...)
      type: text
      name: address
      optional: false
      label: _(The approximate address or location of my project is...)
      attrs:
        - key: placeholder
          value: _(Let us know where you mean.)
        - key: maxlength
          value: 160
    - prompt: _(Show us with a picture)
      inputfile_label: _(Upload an image)
      type: file
      name: my_image
      attrs:
        - key: accept
          value: image/*
    - prompt: _(Add a link)
      type: text
      name: infolink
      attrs:
        - key: placeholder
          value: _(Add a related link (an example or more info))
        - key: size
          value: 30
    - type: hidden
      name: private-conf
      attrs:
        - key: value
          value: "Not sent"
    - prompt: _(* Your Name)
      label: _(Suggested by)
      type: text
      name: submitter_name
      attrs:
        - key: placeholder
          value: _(Person/Org to be credited for idea publicly)
        - key: size
          value: 30
        - key: required
          value: required
    - prompt: _(Your organization)
      label: _(Organization)
      type: text
      name: organization
      attrs:
        - key: placeholder
          value: _(Your organization)
        - key: size
          value: 30
    - prompt: _(* Your email)
      type: email
      optional: false
      name: private-email
      attrs:
        - key: placeholder
          value: _(Your email will not be shown publicly)
        - key: size
          value: 30
        - key: required
          value: required
    - prompt: _(Your phone number)
      type: text
      name: private-phone
      attrs:
        - key: placeholder
          value: _(Your number will not be shown publicly)
        - key: size
          value: 30

survey:
  submission_type: comments
  adding_supported: false

  # Response config
  show_responses: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items: []

support:
  submission_type: support
  adding_supported: false
  submit_btn_text: _(Like This!)
  response_name: _(like)
  response_plural_name: _(likes)
  action_text: liked
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true
  - title: Filter Past Winners
    slug: filter-type
    pages:
      - title: All
        external: true
        url: /filter/all
      - title: _(2018)
        url: /filter/Winner2018
        external: true
      - title: _(2017)
        url: /filter/Winner2017
        external: true
      - title: _(2016)
        url: /filter/Winner2016
        external: true
      - title: _(2015)
        url: /filter/Winner2015
        external: true
      - title: _(2014)
        url: /filter/Winner2014
        external: true
      - title: _(2013)
        url: /filter/Winner2013
        external: true
  - title: _(2019 Public Space Challenge)
    slug: challenge
    external: true
    url: https://www.publicspacechallenge.org/
